### ISSUE TITLE
It shows "INVALID_CLIENT: Invalid redirect URI" when it opens the webpage after asking for my client id and secret

### ISSUE THREAD

**Issue by msr8** [Reverend-Toady/random-playlist-maker#1]
Here is the link it redirected me to:
`https://accounts.spotify.com/authorize?client_id=8d151f78ca844eb59446100a4408e4a7&response_type=code&redirect_uri=http%3A%2F%2Fexample.com%2Fcallback%2F&scope=playlist-modify-public+user-library-read+playlist-read-private+playlist-modify-private`

Screenshots:
![Screenshot 2022-03-14 at 17 09 42](https://user-images.githubusercontent.com/79649185/158164752-4d8bd174-9ab7-4fc8-972c-9a6725b8b9a9.png)
![Screenshot 2022-03-14 at 17 09 05](https://user-images.githubusercontent.com/79649185/158164664-2f2a1a22-a85c-487e-b3d3-7dc062d36042.png)

**Comment by Aditya-Jyoti** [comment]
Did not expect this issue to arise,

firstly in the root directory of the project remove any `.cache` files that you see, something like `$ rm .cache` should work

next in the [spotify developer dashboard](https://developer.spotify.com/dashboard/applications) click on your application and go to the settings tab

![Screenshot_20220314_171756](https://user-images.githubusercontent.com/75803854/158166646-dd25548d-1b50-4a69-ac57-41d1c0b171b8.png)

here you should see a `callback` section 

![Screenshot_20220314_171904](https://user-images.githubusercontent.com/75803854/158166684-3d217d5f-7c54-4275-92fd-a2beb903a555.png)

in that please add the following url just as is `http://example.com/callback/`

now refresh the page and give a few moments for the changes to take place and try running the app again, please do make sure to remove and `.cache` files

**Comment by Aditya-Jyoti** [comment]
if this solves the issue will be adding solution to documentation

**Comment by msr8** [comment]
Ohhh yes I forgot I had added that for another application I was testing, my bad, thanks for the help!
